### ISSUE TITLE
problem in decoding time

### ISSUE THREAD

**Issue by G-Pavel** [codemation/easyschedule#1]
Hello,
There seems to be a problem in decoding the time, for example:
"5,32 0,1,2,3,4 * * *"
"You" don't understand the symbol ",".

And that doesn't work either:
"* * * * 7"
Number instead of the name of the day of the week

These are working examples at https://crontab.guru/

Could you please fix this.

**Comment by codemation** [comment]
@G-Pavel  thanks for opening the issue, I was able to reproduce the same issues with the provided cron schedules. 

I corrected the parsing to handle weekdays as numbers. Comma separated days should also now correctly parsed:

https://pypi.org/project/easyschedule/0.105/

Try to pip install -U easyschedule - might need to run this twice to get latest version.

Try it out and Close the Issue if you are happy.

**Comment by G-Pavel** [comment]
Hi, previous mistakes were corrected, thanks!

But I found a few more:
1. I do not understand why the scheduler always increases one minute?
For example, code:
`"3 10 * * *"`
launched at:
2021-04-15 10:04:00
instead
2021-04-15 10:03:00
2. Schedule
`"* * 18 * 1"`
launched at:
2021-10-18 00:01:00
instead
2021-04-18 00:00:00
3. And this schedule does not work:
`"* * * 2,3 *"`

Could you please fix this too?

**Comment by codemation** [comment]
@G-Pavel - https://pypi.org/project/easyschedule/0.106/ - should contain the fix for the minute skew that you reported. 

If nothing else, feel free to close & enjoy. Thanks for the contribution.
